require('./gulp/tasks/pug');
require('./gulp/tasks/styles');
require('./gulp/tasks/ImageMin');
require('./gulp/tasks/clean');
require('./gulp/tasks/production');
require('./gulp/tasks/watch');
require('./gulp/tasks/symbols');
require('./gulp/tasks/copy');
require('./gulp/tasks/gh-pages');